version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Sao_Paulo"
    cooldown:
      default-days: 4
    groups:
      non-major:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Sao_Paulo"
    cooldown:
      default-days: 4
    groups:
      actions:
        applies-to: version-updates
        patterns:
          - "*"
